commit_message: '[skip ci]'
files:
  - source: /docs/src/**/*.md
    ignore:
      - /%original_path%/%file_name%-%two_letters_code%.md
      - /docs/src/pages/getting-started/templates/
      - /docs/src/pages/premium-themes/
      - /docs/src/pages/discover-more/backers/
      - /docs/src/pages/discover-more/roadmap/
      - /docs/src/pages/company/
    translation: /%original_path%/%file_name%-%two_letters_code%.md
  - source: /docs/translations/*.json
    ignore:
      - /%original_path%/%file_name%-%two_letters_code%.%file_extension%
    translation: /%original_path%/%file_name%-%two_letters_code%.%file_extension%
